name: Release

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PAT }}

jobs:
  build-image-arm64:
    runs-on: build-arm64-big

    strategy:
      matrix:
        include:
          - partition: ./bellis
            image: daisytuner/bellis
            platform: linux/arm64
          - partition: ./tansy
            image: daisytuner/tansy
            platform: linux/arm64
          - partition: ./aster
            image: daisytuner/aster
            platform: linux/arm64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Extract short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.partition }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ matrix.image }}:${{ env.SHORT_SHA }}
            ${{ matrix.image }}:latest

  build-image-amd64:
    runs-on: build-amd64-big
    env:
      TT_METAL_VERSION: "v0.63.0"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Extract short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./x64-base
          platforms: linux/amd64
          push: true
          tags: |
            daisytuner/x64-base:${{ env.SHORT_SHA }}
            daisytuner/x64-base:latest
            daisytuner/chamomile:${{ env.SHORT_SHA }}
            daisytuner/chamomile:latest
            daisytuner/zinnia:${{ env.SHORT_SHA }}
            daisytuner/zinnia:latest

      - name: Build and Push Tenstorrent Derivative Image
        uses: docker/build-push-action@v5
        with:
          context: ./x64-tenstorrent
          platforms: linux/amd64
          push: true
          build-args: |
            TT_METAL_VERSION=${{ env.TT_METAL_VERSION }}
          tags: |
            daisytuner/x64-tenstorrent:${{ env.TT_METAL_VERSION }}-${{ env.SHORT_SHA }}
            daisytuner/x64-tenstorrent:${{ env.TT_METAL_VERSION }}-latest
